# Generated by Django 6.1 on 2026-08-09 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_value', models.CharField(max_length=64)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='idcards/barcodes/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_card', to='accounts.studentprofile')),
            ],
        ),
    ]
