# Generated by Django 6.1 on 2026-08-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentidcard',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='idcards/qr/'),
        ),
    ]
