# Generated by Django 6.1 on 2026-08-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='promotion_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('promoted', 'Promoted'), ('retained', 'Retained'), ('graduated', 'Graduated')], default='pending', max_length=16),
        ),
    ]
