# Generated by Django 6.1 on 2026-08-10 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_admission_enroll_fields'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='blood_group',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='application',
            name='city_of_residence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='disability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='enrolled_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_applications', to='accounts.studentprofile'),
        ),
        migrations.AddField(
            model_name='application',
            name='father_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='father_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='father_whatsapp',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='genotype',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='application',
            name='hometown',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='lga',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_whatsapp',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='next_of_kin_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='applications/photos/'),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='application',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
