# Generated by Django 6.1 on 2026-08-09 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ca2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exam', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academics.classarm')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_scores', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academics.term')),
            ],
            options={
                'unique_together': {('student', 'subject', 'term')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=16)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academics.classarm')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='accounts.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academics.term')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FormClassRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_class', models.PositiveIntegerField(default=0)),
                ('date_of_resumption', models.DateField(blank=True, null=True)),
                ('next_term_resumption', models.DateField(blank=True, null=True)),
                ('days_opened', models.PositiveIntegerField(default=0)),
                ('teacher_remark_template', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_records', to='academics.classarm')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_records', to='academics.term')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('class_arm', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentFormRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_present', models.PositiveIntegerField(default=0)),
                ('days_absent', models.PositiveIntegerField(default=0)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('teacher_remark', models.TextField(blank=True)),
                ('punctuality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('neatness', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('politeness', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('honesty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cooperation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('leadership', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('handwriting', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sports', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tool_handling', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classarm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_records', to='accounts.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_form_records', to='academics.term')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
    ]
