# Generated by Django 6.1 on 2026-08-09 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.staffprofile'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='term',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicsession'),
        ),
        migrations.AlterUniqueTogether(
            name='classarm',
            unique_together={('class_level', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'class_level')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('staff', 'class_arm', 'subject', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('session', 'number')},
        ),
    ]
