# Generated by Django 6.1 on 2026-08-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherassignment',
            options={'ordering': ['staff__full_name', 'class_arm__label', 'subject__name']},
        ),
    ]
