# Generated by Django 6.1 on 2026-08-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_term_results_entry_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='students_promoted_for_session',
            field=models.BooleanField(default=False, help_text='True after students were auto-promoted when this session became active.'),
        ),
    ]
