# Generated by Django 6.1 on 2026-08-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_session_students_promoted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First Term'), (2, 'Second Term'), (3, 'Third Term')]),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(condition=models.Q(('number__in', [1, 2, 3])), name='term_number_first_second_or_third'),
        ),
    ]
