# Generated by Django 6.1 on 2026-08-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_normalize_session_terms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["class_level__order", "order", "name"]},
        ),
        migrations.AddField(
            model_name="subject",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Display order within the class level (lower first).",
            ),
        ),
    ]
