# Generated by Django 6.1 on 2026-08-12 13:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0009_sync_nursery_daycare_subjects'),
        ('accounts', '0004_admission_enroll_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CbtPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('paper_type', models.CharField(choices=[('normal', 'Normal CBT')], default='normal', max_length=16)),
                ('score_component', models.CharField(choices=[('ca1', 'CA1'), ('ca2', 'CA2'), ('exam', 'Exam')], max_length=8)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_papers', to='academics.classarm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbt_papers_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_papers', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_papers', to='academics.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CbtAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('earned_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('paper_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('scaled_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted')], default='in_progress', max_length=16)),
                ('written_to_results', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_attempts', to='accounts.studentprofile')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cbt.cbtpaper')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('paper', 'student')},
            },
        ),
        migrations.CreateModel(
            name='CbtQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cbt.cbtpaper')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('paper', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CbtChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='cbt.cbtquestion')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('question', 'label')},
            },
        ),
        migrations.CreateModel(
            name='JambAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='JAMB Practice', max_length=255)),
                ('score_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('subjects_json', models.JSONField(blank=True, default=list)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, default='pending_integration', help_text='Filled when the external JAMB CBT repo is wired in.', max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jamb_attempts', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='CbtAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cbt.cbtattempt')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='cbt.cbtchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cbt.cbtquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
