# Generated by Django 6.1 on 2026-08-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Inventories'},
        ),
    ]
